export interface IMovieSub{
    "cast_id":number,
    "character": string,
    "credit_id": string,
    "gender": number,
    "id": number,
    "name": string,
    "order": number,
    "profile_path": string,
    "aspect_ratio":number,
    "file_path":string,
    "height":number,
    "iso_639_1":string,
    "vote_average":number,
    "vote_count":number,
    "width":number,
    "title":string,
    "department":string,
    "job":string,
   "known_for_department":string,
   "release_date":string,
   "type":string,
   "key":string,
    backdrop_path: string,
      poster_path: string,
      popularity: number,
      video: boolean
     
}