export interface IMovie{
    "popularity": number,
      "id": number,
      "video": boolean,
      "vote_count": number,
      "vote_average":  number,
      "title": string,
      "release_date": string,
      "original_language": string,
      "original_title": string,
      "genre_ids": [],
      "backdrop_path": string,
      "adult": boolean,
      "overview": string,
      "poster_path": string,
      "genres":[],
      "budget":number,
      "revenue": number,
      "runtime": number,
      "tagline":string,
      "homepage":string,
      "status": string
}